services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: secondand15
      POSTGRES_PASSWORD: secondand15
      POSTGRES_USER: secondand15
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U secondand15 -d secondand15']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
