export const HISTORICAL_SCHEMA_VERSION = 'nflverse-2026-08-03';
export const HISTORICAL_MAPPING_VERSION = 'player-stats-v1';
export const HISTORICAL_AGGREGATION_VERSION = 'weekly-sum-v1';

export type SourcePhysicalType = 'BYTE_ARRAY' | 'INT32' | 'INT64' | 'FLOAT' | 'DOUBLE' | 'BOOLEAN';

export interface HistoricalFieldMapping {
  readonly source: string;
  readonly internal: string;
  readonly type: SourcePhysicalType;
  readonly required: boolean;
  readonly nullable: boolean;
  readonly unit: string;
  readonly description: string;
  readonly transformation: string;
  readonly firstSupportedSeason?: number;
}

const identity = (
  source: string,
  internal: string,
  type: SourcePhysicalType,
  description: string,
): HistoricalFieldMapping => ({
  source,
  internal,
  type,
  required: true,
  nullable: false,
  unit: 'identifier',
  description,
  transformation: 'Trimmed and validated; never matched by player name alone.',
});

const count = (source: string, internal: string, description: string): HistoricalFieldMapping => ({
  source,
  internal,
  type: 'INT32',
  required: false,
  nullable: true,
  unit: 'count',
  description,
  transformation: 'Preserved as nullable integer; missing is not converted to zero.',
});

const yards = (source: string, internal: string, description: string): HistoricalFieldMapping => ({
  ...count(source, internal, description),
  unit: 'yards',
});

const metric = (source: string, internal: string, description: string): HistoricalFieldMapping => ({
  source,
  internal,
  type: 'DOUBLE',
  required: false,
  nullable: true,
  unit: 'source-defined decimal',
  description,
  transformation: 'Preserved as nullable finite number using the nflverse definition.',
});

export const NFLVERSE_PLAYER_STAT_FIELDS = [
  identity('player_id', 'playerId', 'BYTE_ARRAY', 'GSIS player identifier.'),
  identity('game_id', 'gameId', 'BYTE_ARRAY', 'nflverse stable game identifier.'),
  identity(
    'team',
    'teamId',
    'BYTE_ARRAY',
    'Source team abbreviation resolved to an internal team.',
  ),
  identity(
    'opponent_team',
    'opponentTeamId',
    'BYTE_ARRAY',
    'Opponent abbreviation resolved to an internal team.',
  ),
  identity('season', 'season', 'INT32', 'NFL season.'),
  identity('week', 'week', 'INT32', 'NFL week.'),
  identity('season_type', 'seasonType', 'BYTE_ARRAY', 'PRE, REG, or POST season type.'),
  count('completions', 'completions', 'Completed passes.'),
  count('attempts', 'attempts', 'Pass attempts.'),
  yards('passing_yards', 'passingYards', 'Passing yards.'),
  count('passing_tds', 'passingTouchdowns', 'Passing touchdowns.'),
  count('passing_interceptions', 'passingInterceptions', 'Passes intercepted.'),
  count('sacks_suffered', 'sacksSuffered', 'Sacks suffered by passer.'),
  yards('sack_yards_lost', 'sackYardsLost', 'Signed yards lost on sacks.'),
  yards('passing_air_yards', 'passingAirYards', 'Passing air yards.'),
  yards(
    'passing_yards_after_catch',
    'passingYardsAfterCatch',
    'Yards after catch on completed passes.',
  ),
  count('passing_first_downs', 'passingFirstDowns', 'Passing first downs.'),
  metric('passing_epa', 'passingEpa', 'Source passing expected points added.'),
  count('passing_2pt_conversions', 'passing2ptConversions', 'Passing two-point conversions.'),
  count('carries', 'carries', 'Rushing attempts.'),
  yards('rushing_yards', 'rushingYards', 'Rushing yards; may legitimately be negative.'),
  count('rushing_tds', 'rushingTouchdowns', 'Rushing touchdowns.'),
  count('rushing_first_downs', 'rushingFirstDowns', 'Rushing first downs.'),
  metric('rushing_epa', 'rushingEpa', 'Source rushing expected points added.'),
  count('rushing_fumbles', 'rushingFumbles', 'Fumbles on rushing plays.'),
  count('rushing_fumbles_lost', 'rushingFumblesLost', 'Lost fumbles on rushing plays.'),
  count('rushing_2pt_conversions', 'rushing2ptConversions', 'Rushing two-point conversions.'),
  count('targets', 'targets', 'Receiving targets.'),
  count('receptions', 'receptions', 'Receptions.'),
  yards('receiving_yards', 'receivingYards', 'Receiving yards; may legitimately be negative.'),
  count('receiving_tds', 'receivingTouchdowns', 'Receiving touchdowns.'),
  yards(
    'receiving_air_yards',
    'receivingAirYards',
    'Receiving air yards; may legitimately be negative.',
  ),
  yards(
    'receiving_yards_after_catch',
    'receivingYardsAfterCatch',
    'Receiving yards after catch; may be negative.',
  ),
  count('receiving_first_downs', 'receivingFirstDowns', 'Receiving first downs.'),
  metric('receiving_epa', 'receivingEpa', 'Source receiving expected points added.'),
  metric('target_share', 'targetShare', 'Source-provided target share.'),
  count('receiving_2pt_conversions', 'receiving2ptConversions', 'Receiving two-point conversions.'),
  count('fumbles_total', 'fumbles', 'All recorded fumbles.'),
  count('fumbles_lost_total', 'fumblesLost', 'All recorded lost fumbles.'),
  count('def_tackles_solo', 'tacklesSolo', 'Solo tackles.'),
  count('def_tackles_with_assist', 'tacklesWithAssist', 'Tackles credited with an assist.'),
  count('def_tackle_assists', 'tackleAssists', 'Tackle assists.'),
  count('def_tackles_for_loss', 'tacklesForLoss', 'Tackles for loss.'),
  metric('def_sacks', 'defensiveSacks', 'Defensive sacks, including half-sacks.'),
  metric('def_sack_yards', 'defensiveSackYards', 'Defensive sack yards.'),
  count('def_qb_hits', 'quarterbackHits', 'Quarterback hits.'),
  count('def_interceptions', 'defensiveInterceptions', 'Defensive interceptions.'),
  yards('def_interception_yards', 'interceptionYards', 'Interception return yards.'),
  count('def_pass_defended', 'passesDefended', 'Passes defended.'),
  count('def_fumbles_forced', 'forcedFumbles', 'Forced fumbles.'),
  count('fumble_recovery_opp', 'fumbleRecoveries', 'Opponent fumbles recovered.'),
  count('def_tds', 'defensiveTouchdowns', 'Defensive touchdowns.'),
  count('fg_made', 'fieldGoalsMade', 'Field goals made.'),
  count('fg_att', 'fieldGoalsAttempted', 'Field goals attempted.'),
  count('pat_made', 'extraPointsMade', 'Point-after kicks made.'),
  count('pat_att', 'extraPointsAttempted', 'Point-after kicks attempted.'),
  count('pt_att', 'punts', 'Punts.'),
  yards('pt_yards', 'puntYards', 'Punt yards.'),
  yards('punt_return_yards', 'puntReturnYards', 'Punt return yards; may be negative.'),
  count('pt_return_tds', 'puntReturnTouchdowns', 'Punt return touchdowns.'),
  yards('kickoff_return_yards', 'kickoffReturnYards', 'Kickoff return yards.'),
  count('special_teams_tds', 'specialTeamsTouchdowns', 'Source special-teams touchdowns.'),
  metric('fantasy_points', 'fantasyPointsStandard', 'nflverse standard fantasy points.'),
  metric('fantasy_points_ppr', 'fantasyPointsPpr', 'nflverse PPR fantasy points.'),
] as const satisfies readonly HistoricalFieldMapping[];

export const NFLVERSE_PLAYER_REQUIRED_COLUMNS = [
  'gsis_id',
  'display_name',
  'first_name',
  'last_name',
] as const;

export const NFLVERSE_ROSTER_REQUIRED_COLUMNS = [
  'season',
  'team',
  'position',
  'full_name',
  'week',
  'game_type',
  'gsis_id',
  'smart_id',
] as const;

export const NFLVERSE_PLAYER_COLUMNS = [
  'gsis_id',
  'display_name',
  'common_first_name',
  'first_name',
  'last_name',
  'short_name',
  'football_name',
  'suffix',
  'esb_id',
  'nfl_id',
  'pfr_id',
  'pff_id',
  'otc_id',
  'espn_id',
  'smart_id',
  'birth_date',
  'position_group',
  'position',
  'ngs_position_group',
  'ngs_position',
  'height',
  'weight',
  'headshot',
  'college_name',
  'college_conference',
  'jersey_number',
  'rookie_season',
  'last_season',
  'latest_team',
  'status',
  'ngs_status',
  'ngs_status_short_description',
  'years_of_experience',
  'pff_position',
  'pff_status',
  'draft_year',
  'draft_round',
  'draft_pick',
  'draft_team',
] as const;

export const NFLVERSE_PLAYER_IMPORTED_COLUMNS = [
  'gsis_id',
  'display_name',
  'first_name',
  'last_name',
  'short_name',
  'football_name',
  'esb_id',
  'nfl_id',
  'pfr_id',
  'pff_id',
  'otc_id',
  'espn_id',
  'smart_id',
  'birth_date',
  'position_group',
  'position',
  'height',
  'weight',
  'headshot',
  'college_name',
  'jersey_number',
  'rookie_season',
  'last_season',
  'latest_team',
  'status',
  'draft_year',
  'draft_round',
  'draft_pick',
  'draft_team',
] as const;

export const NFLVERSE_ROSTER_COLUMNS = [
  'season',
  'team',
  'position',
  'depth_chart_position',
  'jersey_number',
  'status',
  'full_name',
  'first_name',
  'last_name',
  'birth_date',
  'height',
  'weight',
  'college',
  'gsis_id',
  'espn_id',
  'sportradar_id',
  'yahoo_id',
  'rotowire_id',
  'pff_id',
  'pfr_id',
  'fantasy_data_id',
  'sleeper_id',
  'years_exp',
  'headshot_url',
  'ngs_position',
  'week',
  'game_type',
  'status_description_abbr',
  'football_name',
  'esb_id',
  'gsis_it_id',
  'smart_id',
  'entry_year',
  'rookie_year',
  'draft_club',
  'draft_number',
] as const;

export const NFLVERSE_ROSTER_IMPORTED_COLUMNS = [
  'season',
  'team',
  'position',
  'depth_chart_position',
  'jersey_number',
  'status',
  'full_name',
  'first_name',
  'last_name',
  'gsis_id',
  'espn_id',
  'sportradar_id',
  'yahoo_id',
  'pff_id',
  'pfr_id',
  'sleeper_id',
  'years_exp',
  'headshot_url',
  'week',
  'game_type',
  'status_description_abbr',
  'football_name',
  'esb_id',
  'smart_id',
] as const;

export const NFLVERSE_PLAYER_STAT_COLUMNS = [
  'player_id',
  'player_name',
  'player_display_name',
  'position',
  'position_group',
  'headshot_url',
  'season',
  'week',
  'season_type',
  'game_id',
  'team',
  'opponent_team',
  'completions',
  'attempts',
  'passing_yards',
  'passing_tds',
  'passing_interceptions',
  'sacks_suffered',
  'sack_yards_lost',
  'sack_fumbles',
  'sack_fumbles_lost',
  'passing_air_yards',
  'passing_yards_after_catch',
  'passing_first_downs',
  'passing_epa',
  'passing_cpoe',
  'passing_2pt_conversions',
  'pacr',
  'passing_10',
  'passing_16',
  'passing_20',
  'passing_40',
  'carries',
  'rushing_yards',
  'rushing_tds',
  'rushing_fumbles',
  'rushing_fumbles_lost',
  'rushing_first_downs',
  'rushing_epa',
  'rushing_2pt_conversions',
  'rushing_10',
  'rushing_12',
  'rushing_20',
  'rushing_40',
  'receptions',
  'targets',
  'receiving_yards',
  'receiving_tds',
  'receiving_fumbles',
  'receiving_fumbles_lost',
  'receiving_air_yards',
  'receiving_yards_after_catch',
  'receiving_first_downs',
  'receiving_epa',
  'receiving_2pt_conversions',
  'receiving_10',
  'receiving_16',
  'receiving_20',
  'receiving_40',
  'racr',
  'target_share',
  'air_yards_share',
  'wopr',
  'special_teams_tds',
  'def_tackles_solo',
  'def_tackles_with_assist',
  'def_tackle_assists',
  'def_tackles_for_loss',
  'def_tackles_for_loss_yards',
  'def_fumbles_forced',
  'def_sacks',
  'def_sack_yards',
  'def_qb_hits',
  'def_interceptions',
  'def_interception_yards',
  'def_pass_defended',
  'def_tds',
  'def_fumbles',
  'def_safeties',
  'misc_yards',
  'fumble_recovery_own',
  'fumble_recovery_yards_own',
  'fumble_recovery_opp',
  'fumble_recovery_yards_opp',
  'fumble_recovery_tds',
  'penalties',
  'penalty_yards',
  'fumbles_forced_by_opp',
  'fumbles_not_forced',
  'fumbles_out_of_bounds',
  'fumbles_total',
  'fumbles_lost_total',
  'punt_returns',
  'punt_return_yards',
  'kickoff_returns',
  'kickoff_return_yards',
  'fg_made',
  'fg_att',
  'fg_missed',
  'fg_blocked',
  'fg_long',
  'fg_pct',
  'fg_made_0_19',
  'fg_made_20_29',
  'fg_made_30_39',
  'fg_made_40_49',
  'fg_made_50_59',
  'fg_made_60_',
  'fg_missed_0_19',
  'fg_missed_20_29',
  'fg_missed_30_39',
  'fg_missed_40_49',
  'fg_missed_50_59',
  'fg_missed_60_',
  'fg_made_list',
  'fg_missed_list',
  'fg_blocked_list',
  'fg_made_distance',
  'fg_missed_distance',
  'fg_blocked_distance',
  'pat_made',
  'pat_att',
  'pat_missed',
  'pat_blocked',
  'pat_pct',
  'gwfg_made',
  'gwfg_att',
  'gwfg_missed',
  'gwfg_blocked',
  'gwfg_distance',
  'pt_att',
  'pt_blocked',
  'pt_long',
  'pt_yards',
  'pt_inside_20',
  'pt_out_of_bounds',
  'pt_downed',
  'pt_touchback',
  'pt_fair_caught',
  'pt_returned',
  'pt_return_yards',
  'pt_return_tds',
  'pt_net_yards',
  'fantasy_points',
  'fantasy_points_ppr',
] as const;

export const NFLVERSE_PLAYER_STAT_IMPORTED_COLUMNS = new Set(
  NFLVERSE_PLAYER_STAT_FIELDS.map((field) => field.source).concat([
    'player_name',
    'player_display_name',
    'position',
    'position_group',
    'headshot_url',
  ]),
);
